### ISSUE TITLE
Add more meta information for links and ports

### ISSUE THREAD

**Issue by leMaik** [BuggyOrg/graphlib2kgraph#1]
At the moment, the links and ports have only their types as meta information. To display more helpful tooltips in graphify, it would be useful to add the following information:

Ports:
- [x] Port type
- [ ] Port name

Links:
- [x] Link type
- [ ] Start node
- [ ] Start port
- [ ] End node
- [ ] End port

Please feel free to continue these lists. :wink:

**Comment by LittleHelicase** [comment]
Fixed with e845c7a9375f010c291e8af3cfb84c2884d6f482
